export default{
	INDUSTRIES:[
		{industry:"Saas Product",key:2},
		{industry:"Advertising Agency",key:2},
		{industry:"Animal Focused Platform",key:2},
		{industry:"Finance Techology",key:2},
		{industry:"Healthcare",key:2},
		{industry:"Personal Health Techology",key:2},
		{industry:"Fitness Agency",key:2},
		{industry:"Media Agency",key:2},
		{industry:"Education Technology",key:2},
		{industry:"Health and Wellness",key:2},
		{industry:"Web Development ",key:2},
		{industry:"Mobile Application",key:2},
		{industry:"Food Startups",key:2},
		{industry:"Retail ",key:2},
		{industry:"Artificial Intelligence Technology",key:2},
		{industry:"Virtual Reality Platform",key:2},
		{industry:"Messaging platform",key:2},
		{industry:"Design",key:2},
		{industry:"Gaming",key:2},
		{industry:"Analytics Platform",key:2},
		{industry:"Life Sciences",key:2},
		{industry:"Automotive",key:2},
		{industry:"Fashion ",key:2},
		{industry:"Travel and Tourism Agency",key:2},
		{industry:"Digital Marketing ",key:2},
		{industry:"Business Platform",key:2},
		{industry:"Entertainment App",key:2},
		{industry:"Sports Platform/Agency",key:2},
		{industry:"Cloud Computing Services",key:2},
		{industry:"Ecommerce Platform",key:2},
		{industry:"Clean Technology ",key:2},
		{industry:"FinTech",key:2},
		{industry:"Entertainment Industry",key:2},
		{industry:"Energy",key:2},
		{industry:"BioTechnology Startup",key:2},
		{industry:"Robotics Startup",key:2},
		{industry:"Solar Powered Startup",key:2},
		{industry:"Engineering Agencies ",key:2},
		{industry:"Legal, Complaince, and HR agency",key:2},
		{industry:"Blockchains ",key:2},
		{industry:"Blogging Platforms",key:2},
		{industry:"Events Agency",key:2},
		{industry:"Consulting",key:2},
		{industry:"Entertainment ",key:2},
		{industry:"Education Technology",key:2},
		{industry:"Restaurants",key:2},
		{industry:"Blockchain / Cryptocurrency ",key:2},
		{industry:"Manufacturing",key:2},
		{industry:"Hospitality",key:2},
		{industry:"Human Resources",key:2},
		{industry:"Construction",key:2},
		{industry:"Digital Agency",key:2},
		{industry:"Agriculture",key:2},
		{industry:"Beauty",key:2},
		{industry:"Logistics",key:2},
		{industry:"Art Platform",key:2},
		{industry:"Music Platform/Agency",key:2},
		{industry:"New Innovative Technology",key:2},
		{industry:"Movie Platform",key:2},
		{industry:"User Experience Design Agency",key:2}
	]
}