export default{
	INDUSTRIES:[
		{ industry:"Photography",
			subCommunity:[
				{industry:"Landscape"},
				{industry:"Wildlife"},
				{industry:"Aerial"},
				{industry:"Sports"},
				{industry:"Portrait"},
				{industry:"Fashion"}
			],
			id:1 },
		{ industry:"Gaming",
			subCommunity:[
				{industry:"Super Smash Bros"},
				{industry:"Call of duty"},
				{industry:"Fornite"},
				{industry:"Overwatch"},
				{industry:"League of Legends"},
				{industry:"Elder Scrolls"},
				{industry:"Marvel Games"},
				{industry:"Counter Strike"},
				{industry:"World of Warcraft"},
				{industry:"Elder Scrolls"},
				{industry:"Minecraft"},
				{industry:"Sports"},
				{industry:"Actions"},
				{industry:"Battle Royale"},
				{industry:"Action Adventure"},
				{industry:"Role-playing"},
				{industry:"Adventure"},
				{industry:"Racing"},
				{industry:"Fighting"},
				{industry:"Simulator"}
			],id:2 },
		{ industry:"TV Shows",
			subCommunity:[
				{industry:"Drama"},
				{industry:"Comedy"},
				{industry:"Reality"},
				{industry:"News"},
				{industry:"Sports"},
				{industry:"Documentary"},
				{industry:"Game of Thrones"},
				{industry:"Breaking Bad"},
				{industry:"Rick and Morty"},
				{industry:"The Sopranos"},
				{industry:"Friends"},
				{industry:"The Office"},
				{industry:"Black Mirror"},
				{industry:"Curb Your Enthusiam"},
				{industry:"Walking dead"},
				{industry:"American Horror Story"},
				{industry:"Riverdale"},
				{industry:"Orange is the new black"}
			],id:3},
		{ industry:"Movies",subCommunity:[
				{industry:"Action"},
				{industry:"Adventure"},
				{industry:"Comedy"},
				{industry:"Crime"},
				{industry:"Drama"},
				{industry:"Fantasy"},
				{industry:"Horror"},
				{industry:"Science Fiction"}
			],id:1 },
		{ industry:"Music",subCommunity:[
				{industry:"Jazz"},
				{industry:"Rap"},
				{industry:"Hip Hop"},
				{industry:"Blues"},
				{industry:"Rock"},
				{industry:"Folk Music"},
				{industry:"Reggae"},
				{industry:"Pop Music"},
				{industry:"Heavy Metal"},
				{industry:"Orchestra"},
				{industry:"Instrumental"},
				{industry:"Pop Music"}
			],id:2 },
		{ industry:"News",
			subCommunity:[
				{industry:"Sports"},
				{industry:"Technology"},
				{industry:"Weather"},
				{industry:"Current Events"},
				{industry:"Breaking News"},
				{industry:"Government"},
				{industry:"Environmental"},
				{industry:"World Wide"}
			],id:3},
		{ industry:"Social Sciences And Managment",id:1 },
		{ industry:"Finance",id:2 },
		{ industry:"Arts & Humanities",id:3},
		{ industry:"Law",id:1 },
		{ industry:"Medicine",id:2 },
		{ industry:"Art",
			subCommunity:[
				{industry:"Graffiti"},
				{industry:"Animation"},
				{industry:"Street Art"},
				{industry:"Illustration"},
				{industry:"Life Drawings"},
				{industry:"Paintings"},
				{industry:"Digital Art"},
				{industry:"Contemporary Art"}
			],id:3},
		{ industry:"Graphic Design",
			subCommunity:[
				{industry:"User Interface Graphics"},
				{industry:"Art And Illustrations"},
				{industry:"Environmental Graphics"},
				{industry:"Illustration And posters"}
			],id:1 },
		{ industry:"Design",
			subCommunity:[
				{industry:"Architecture And Interior"},
				{industry:"Garden And Landscape"},
				{industry:"Product Design"},
				{industry:"Furniture Design"}
			],id:2 },
		{ industry:"Anthropology",
		subCommunity:[
				{industry:"Biological"},
				{industry:"Cultural"},
				{industry:"Linguistic"},
				{industry:"Archaeology"}
			],id:3},
		{ industry:"Computer Science",
		subCommunity:[
				{industry:"Artificial Intelligence"},
				{industry:"Computer Architecture and Engineering"},
				{industry:"Computer Graphics and Visualization"},
				{industry:"Computer Networks"},
				{industry:"Databases"},
				{industry:"Information Science"},
				{industry:"Software Engineering"},
				{industry:"Concurrent, Parallel and Distributed Systems"},
				{industry:"Theory of Computation"},
				{industry:"Algorithms and Data Structures"},
				{industry:"Cloud Computing"},
				{industry:"Machine Learning"}
			],id:1 },
		{ industry:"Cooking",id:2 },
		{ industry:"Anime/Manga",
			subCommunity:[
				{industry:"Dragon Ball"},
				{industry:"Computer Architecture and Engineering"},
				{industry:"Computer Graphics and Visualization"},
				{industry:"Computer Networks"},
				{industry:"Databases"},
				{industry:"Information Science"},
				{industry:"Software Engineering"},
				{industry:"Concurrent, Parallel and Distributed Systems"},
				{industry:"Theory of Computation"},
				{industry:"Algorithms and Data Structures"},
				{industry:"Cloud Computing"},
				{industry:"Machine Learning"}
			],
			id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
		{ industry:"Fashion",id:1 },
		{ industry:"Health",id:2 },
		{ industry:"Consulting",id:3},
	]
};