export default{
	INDUSTRIES:[
		{	
			industry:"General",
			id:1
		},
		{ industry:"Photography",
			subCommunity:[
				{industry:"Landscape"},
				{industry:"Wildlife"},
				{industry:"Aerial"},
				{industry:"Sports"},
				{industry:"Portrait"},
				{industry:"Fashion"}
			],
		id:1 },
		{ industry:"Gaming",
			subCommunity:[
				{industry:"Super Smash Bros"},
				{industry:"Call of duty"},
				{industry:"Fornite"},
				{industry:"Overwatch"},
				{industry:"League of Legends"},
				{industry:"Elder Scrolls"},
				{industry:"Marvel Games"},
				{industry:"Counter Strike"},
				{industry:"World of Warcraft"},
				{industry:"Elder Scrolls"},
				{industry:"Minecraft"},
				{industry:"Sports"},
				{industry:"Actions"},
				{industry:"Battle Royale"},
				{industry:"Action Adventure"},
				{industry:"Role-playing"},
				{industry:"Adventure"},
				{industry:"Racing"},
				{industry:"Fighting"},
				{industry:"Simulator"}
			],id:2 },
		{ industry:"TV Shows",
			subCommunity:[
				{industry:"Drama"},
				{industry:"Comedy"},
				{industry:"Reality"},
				{industry:"News"},
				{industry:"Sports"},
				{industry:"Documentary"},
				{industry:"Game of Thrones"},
				{industry:"Breaking Bad"},
				{industry:"Rick and Morty"},
				{industry:"The Sopranos"},
				{industry:"Friends"},
				{industry:"The Office"},
				{industry:"Black Mirror"},
				{industry:"Curb Your Enthusiam"},
				{industry:"Walking dead"},
				{industry:"American Horror Story"},
				{industry:"Riverdale"},
				{industry:"Orange is the new black"}
			],id:3},
		{ industry:"Movies",subCommunity:[
				{industry:"Action"},
				{industry:"Adventure"},
				{industry:"Comedy"},
				{industry:"Crime"},
				{industry:"Drama"},
				{industry:"Fantasy"},
				{industry:"Horror"},
				{industry:"Science Fiction"}
			],id:1 },
		{ industry:"Music",subCommunity:[
				{industry:"Jazz"},
				{industry:"Rap"},
				{industry:"Hip Hop"},
				{industry:"Blues"},
				{industry:"Rock"},
				{industry:"Folk Music"},
				{industry:"Reggae"},
				{industry:"Pop Music"},
				{industry:"Heavy Metal"},
				{industry:"Orchestra"},
				{industry:"Instrumental"},
				{industry:"Pop Music"}
			],id:2 },
		{ industry:"News",
			subCommunity:[
				{industry:"Sports"},
				{industry:"Technology"},
				{industry:"Weather"},
				{industry:"Current Events"},
				{industry:"Breaking News"},
				{industry:"Government"},
				{industry:"Environmental"},
				{industry:"World Wide"}
			],id:3},
		{ industry:"Social Sciences And Managment",id:1 },
		{ industry:"Finance",id:2 },
		{ industry:"Arts & Humanities",id:3},
		{ industry:"Law",id:1 },
		{ industry:"Medicine",id:2 },
		{ industry:"Art",
			subCommunity:[
				{industry:"Graffiti"},
				{industry:"Animation"},
				{industry:"Street Art"},
				{industry:"Illustration"},
				{industry:"Life Drawings"},
				{industry:"Paintings"},
				{industry:"Digital Art"},
				{industry:"Contemporary Art"}
			],id:3},
		{ industry:"Graphic Design",
			subCommunity:[
				{industry:"User Interface Graphics"},
				{industry:"Art And Illustrations"},
				{industry:"Environmental Graphics"},
				{industry:"Illustration And posters"}
			],id:1 },
		{ industry:"Design",
			subCommunity:[
				{industry:"Architecture And Interior"},
				{industry:"Garden And Landscape"},
				{industry:"Product Design"},
				{industry:"Furniture Design"}
			],id:2 },
		{ industry:"Anthropology",
		subCommunity:[
				{industry:"Biological"},
				{industry:"Cultural"},
				{industry:"Linguistic"},
				{industry:"Archaeology"}
			],id:3},
		{ industry:"Computer Science",
		subCommunity:[
				{industry:"Artificial Intelligence"},
				{industry:"Computer Architecture and Engineering"},
				{industry:"Computer Graphics and Visualization"},
				{industry:"Computer Networks"},
				{industry:"Databases"},
				{industry:"Information Science"},
				{industry:"Software Engineering"},
				{industry:"Concurrent, Parallel and Distributed Systems"},
				{industry:"Theory of Computation"},
				{industry:"Algorithms and Data Structures"},
				{industry:"Cloud Computing"},
				{industry:"Machine Learning"}
			],id:1 },
		{ industry:"Cooking",id:2 },
		{ industry:"Anime/Manga",
			subCommunity:[
				{industry:"Dragon Ball"},
				{industry:"One piece"},
				{industry:"Pokemon"},
				{industry:"Naruto"},
				{industry:"Death Note"},
				{industry:"Detective Conan"},
				{industry:"Attack On Titan"},
				{industry:"Sailor Moon"},
				{industry:"Fullmetal Alchemist"},
				{industry:"Sword Art Online"},
				{industry:"My Hero Academia"},
				{industry:"Black Clover"},
				{industry:"Hunter x Hunter"},
				{industry:"Bleach"},
				{industry:"Cowboy Bebop"}
			],
			id:3},
		{ industry:"Poetry",
			subCommunity:[
				{industry:"Haiku"},
				{industry:"Free Verse"},
				{industry:"Cinquains"},
				{industry:"Epic"},
				{industry:"Ballad"},
				{industry:"Acrostic"},
				{industry:"Sonnets"}
			],id:1 },
		{ industry:"Books",id:2 },
		{ industry:"Comics",
			subCommunity:[
					{industry:"Marvel"},
					{industry:"DC"},
					{industry:"Science Fiction/Fantasy"},
					{industry:"Action"},
					{industry:"Horror"}
				],id:3},
		{ industry:"Science",
			subCommunity:[
					{industry:"Astronomy"},
					{industry:"Biology"},
					{industry:"Chemistry"},
					{industry:"Earth And Sciences"},
					{industry:"Physics"},
					{industry:"Social Sciences"},
					{industry:"Behavorial Sciences"},
					{industry:"Health Sciences"}
				],id:1 },
		{ industry:"Engineering",id:2 },
		{ industry:"Mechanical Engineering",id:3},
		{ industry:"Computer Engineering",id:1 },
		{ industry:"Electrical Engineering",id:2 },
		{ industry:"Mathematics",
			subCommunity:[
					{industry:"Algebra"},
					{industry:"Calculus 1"},
					{industry:"Calculus 2"},
					{industry:"Calculus 3"},
					{industry:"Calculus 4"},
					{industry:"Geometry"},
					{industry:"Topology"},
					{industry:"Combinatorics"},
					{industry:"Logic"},
					{industry:"Number Theory"},
					{industry:"Differential Equations"},
					{industry:"Computation"},
					{industry:"Mathematical Physics"},
					{industry:"Probability and statistics"},
					{industry:"Game Theory"}
				],id:3},
		{ industry:"Civil Engineering",id:1 },
		{ industry:"Chemical Engineering",id:2 },
		{ industry:"Economics",id:3},
		{ industry:"History",
			subCommunity:[
					{industry:"Political History"},
					{industry:"Diplomatics History"},
					{industry:"Cultural History"},
					{industry:"Social History"},
					{industry:"Economic History"},
					{industry:"Intellectual History"}
				],id:1 },
		{ industry:"Animation",
			subCommunity:[
					{industry:"Traditional"},
					{industry:"Digital 2D"},
					{industry:"3D Animation"},
					{industry:"Motion Capture"},
					{industry:"Stop motion"}
				],id:2 },
		{ industry:"ASMR",id:3},
		{ industry:"Beauty",id:1 },
		{ industry:"Fashion",
			subCommunity:[
					{industry:"Vintage Fashion Style"},
					{industry:"Bohemian Fashion Style"},
					{industry:"Chic Fashion Style"},
					{industry:"Artsy Fashion Style"},
					{industry:"Sexy Fashion Style"},
					{industry:"Casual Fashion Style"},
					{industry:"Sophisticated Fashion Style"},
					{industry:"Tomboy Fashion Style"}
				],id:2 },
		{ industry:"Comedy",id:3},
		{ industry:"Vlogs",id:1 },
		{ industry:"DIY",id:2 },
		{ industry:"Family",id:3},
		{ industry:"Health",id:1 },
		{ industry:"Fitness",id:2 },
		{ industry:"Dance",
			subCommunity:[
					{industry:"Contemporary"},
					{industry:"Ballet"},
					{industry:"Jazz"},
					{industry:"Tap Dance"},
					{industry:"Hip Hop"},
					{industry:"Ballroom"}
				],id:3},
		{ industry:"Pranks",id:1 },
		{ industry:"Sports",
			subCommunity:[
					{industry:"Soccer"},
					{industry:"Cricket"},
					{industry:"Field Hockey"},
					{industry:"Tennis"},
					{industry:"Volleyball"},
					{industry:"Table Tennis"},
					{industry:"Football"},
					{industry:"Basketball"},
					{industry:"Baseball"},
					{industry:"Golf"},
					{industry:"Rugby"}
				],id:2 },
		{ industry:"Technology",id:3},
		{ industry:"Travel",id:1 }
	]
};